services:
  database:
    container_name: trax_database
    image: postgres
    restart: always
    shm_size: 512m
    environment:
      POSTGRES_USER: trax
      POSTGRES_PASSWORD: trax123
      POSTGRES_DB: trax
      POSTGRES_MULTIPLE_DATABASES: trax_scheduler_tests,trax_data_tests,trax_e2e_tests,chat_e2e_tests,energyhub_e2e_tests
    tty: true
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh

  rabbitmq:
    container_name: trax_rabbitmq
    image: rabbitmq:4-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
